from typing import Any, Dict
from .base import BaseSkill

class SlideGenerationSkill(BaseSkill):
    """
    プレゼンテーションスライドを生成するスキル
    現在はMarp対応のMarkdownを出力する簡易実装
    """
    @property
    def name(self) -> str:
        return "generate_slides"

    @property
    def description(self) -> str:
        return "指定された構成案に基づいて、Marp対応のMarkdown形式でスライドを生成し、ファイルに保存します。"

    @property
    def parameters(self) -> Dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "description": "Presentation title."
                },
                "content_plan": {
                    "type": "string",
                    "description": "Outline or content plan for the presentation."
                },
                "file_path": {
                    "type": "string",
                    "description": "Output file path (e.g., slides.md)."
                }
            },
            "required": ["title", "content_plan", "file_path"]
        }

    def execute(self, title: str, content_plan: str, file_path: str, **kwargs) -> str:
        try:
            # LLMがコードブロックで囲んで返す場合があるので除去する
            import re
            content_plan = re.sub(r"^```[a-zA-Z]*\n?", "", content_plan.strip())
            content_plan = re.sub(r"\n?```$", "", content_plan.strip())

            # Marp Header
            slide_content = f"""---
marp: true
theme: default
paginate: true
header: '{title}'
footer: 'Generated by AI Agent Platform'
---

# {title}

{content_plan}

"""
            # 簡易的に、content_planをそのまま埋め込むのではなく、
            # 本来はLLMで各スライドの詳細を生成させるべきだが、
            # Skillの役割としては「フォーマットして保存する」ことに徹する。
            # 今回はLLMノードで生成されたMarkdown本文を受け取る想定にするか、
            # あるいはここで少し整形するか。
            # シンプルに書き込み機能としての役割を持たせる。
            
            import os
            os.makedirs(os.path.dirname(os.path.abspath(file_path)), exist_ok=True)
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(slide_content)
            
            return f"Successfully generated slides at {file_path}"
        except Exception as e:
            return f"Error generating slides: {str(e)}"
